### ISSUE TITLE
Typo: Tertiary submission deadline date

### ISSUE THREAD

**Issue by patrickjohncyh** [LangProc/langproc-2017-cw#1]
Original:

> Tertiary: the final fallback, which is scaled by 0.8x. Can be submitted up until two days before the deadline (Sun 27th Mar).

Date should be :

> (Sun 25th Mar)

**Comment by mahudu97** [comment]
> Associated with all deliverables is a time-tracking/project management component (10%). This will be updated as you go along, but the final version is due on Fri 27th March at 22:00, then will be assessed orally at the start of Summer term.

Is the submission date for the management component also wrong, Friday (??) or Tuesday 27th March?

**Comment by m8pple** [comment]
Umm, yes - thanks for those. Apparently I can't count backwards, or at least not consistently.
