### ISSUE TITLE
Error in c_translator_formative.sh

### ISSUE THREAD

**Issue by kyczawon** [LangProc/langproc-2017-cw#11]
When the c_translator_formative.sh is ran on the vagrant virtual machine provided in labs the following error comes up:

> python: command not found

We found that the vagrant environment does not have python installed, so the files need to be run using python3. When all occurrences of python in the c_translator_formative.sh file are changed to python3 everything works!

**Comment by m8pple** [comment]
Thanks - I must have apt-installed without noticing I was doing it.
