### ISSUE TITLE
Deliverable weightings

### ISSUE THREAD

**Issue by edpickup** [LangProc/langproc-2017-cw#2]
Four deliverable items are listed, along with their weightings:

- Test Suite (10%)
- C-translator (20%)
- C-compiler (30%)
- Management component (10%)

Unless I am missing additional deliverable items, this is all of them and adds to 70%. Where is the remaining 30% of the module coming from?

**Comment by mahudu97** [comment]
In class tests / tutorials. 10% each - total of 3 - testing things learned in lectures etc

**Comment by m8pple** [comment]
Yes, as @mahudu97 says these will be the 1 hour tests in weeks 8, 9 and 10,
so Mon 26th Feb, Mon 5th Mar, Mon 12th Mar. They should be on the timetable
overview from the first slides, and in blackboard.

**Comment by edpickup** [comment]
Ah, thank you, I had forgotten this.
